imports:
  - path: neo4j.py
  - path: deployment.py
  - path: loadbalancer.py
  - path: instance_group.py
  - path: standalone_ip_address.py
  - path: firewall.py
  - path: network.py
  - path: core-5.sh
  - path: core-4.4.sh

resources:
  - name: neo4j
    type: neo4j.py
    properties:
      zone: us-east1-b
      graphDatabaseVersion: '5'
      adminPassword: foo123
      nodeType: n2-standard-8
      nodeCount: 1
      diskSize: 20
      diskType: pd-balanced
      installGraphDataScience: True
      graphDataScienceLicenseKey: None
      installBloom: True
      bloomLicenseKey: None
outputs:
  - name: url
    description: URL to access Neo4j Browser
    value: $(ref.neo4j.url)
